Public Enum SimonsReturnValue
    EXTERNAL_INVOKE_ERROR = -3
    INVALIDCOMMAND_PARAMETERS = -2
    GENERAL_ERROR = -1
    NEUTRAL = 0
    VALIDCOMMAND = 1
    VALIDCOMMAND_NORESULTS = 2
    VALIDCOMMAND_TOGGLE_DEBUG_MODE = 3
    VALIDCOMMAND_DEBUG_APP_MODIFIED = 4
    VALIDCOMMAND_DEBUG_READTAG_EXPECT_OBJECTID = 5
    VALIDCOMMAND_SHOWHELP = 6
    VALIDCOMMAND_NEXT_CONTEXT = 7
End Enum
